### ISSUE TITLE
dev build fails

### ISSUE THREAD

**Issue by caco3** [jhass/nextcloud-keeweb#18]
I tried to build it, but get this error:
```
> bin/build refs/heads/master
Lösche npm-debug.log
HEAD ist jetzt bei 234333d... Merge branch 'release-1.3'
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "uninstall" "--save-dev" "electron-prebuilt"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/usr/share/npm/lib/install/deps.js:438:3)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:234:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/usr/share/npm/lib/install/deps.js:230:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/usr/share/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

I am aware that it sais "This is an error with npm itself."
So, does it work for others?

**Comment by jhass** [comment]
I never tried with `master`, does `develop` or `v1.3.1` work for you?

**Comment by caco3** [comment]
Nope, none seems to work:

```
> bin/build develop
```
and
```
> bin/build v1.3.1
```
shows same error.

The highest number I have is 0.2.7:
```
> git show-ref
d8484e81abd97be8ce8a1526f72a49b4b1c7dafb refs/heads/master
d8484e81abd97be8ce8a1526f72a49b4b1c7dafb refs/remotes/origin/HEAD
d8484e81abd97be8ce8a1526f72a49b4b1c7dafb refs/remotes/origin/master
bab1c3b9c680d3744300cb119fdab69b6bc75afa refs/tags/v0.1.0
b20f122b45e03ac762c08341c70668b9a7f0b67d refs/tags/v0.2.0
a078059ab2b92676d24676f194477d1d3980b285 refs/tags/v0.2.1
9083731bc43b173117218ed0bd43e0298dd45aee refs/tags/v0.2.2
54a7115ab1b978528376bd4bd72be62ff16bac00 refs/tags/v0.2.3
e24d695991da36ebf08d0a99a99db37f1aeb2913 refs/tags/v0.2.4
11441d1507e8e3aa779ee6ed5c95b85c8cd33e03 refs/tags/v0.2.5
cbc262ee4f53d84002172807e2d59019ef9c4768 refs/tags/v0.2.6
d8484e81abd97be8ce8a1526f72a49b4b1c7dafb refs/tags/v0.2.7
```

**Comment by jhass** [comment]
Works for me, perhaps it's that I'm on NPM 3.10.6?

**Comment by caco3** [comment]
I don't know. That's the version I got from Kubuntu.
I will close the issue since I have now no need for a dev build as the release works for me.
