### ISSUE TITLE
Error on upgrade from NC v27 to v28 when updating KeeWeb app

### ISSUE THREAD

**Issue by bcutter** [jhass/nextcloud-keeweb#241]
During running `occ upgrade` when keeweb updates, this happens:

```
                 Update app keeweb from App Store
                 Repair step: Register MIME type for "application/x-kdbx"
                 Repair info: Registering the mimetype...
                 An unhandled exception has been thrown:
                 Error: Undefined constant OCA\Keeweb\Migration\RegisterMimeType::CUSTOM_MIMETYPEALIASES in /var/www/nextcloud/apps/keeweb/lib/Migration/RegisterMimeType.php:25
                 Stack trace:
                 #0 /var/www/nextcloud/apps/keeweb/lib/Migration/RegisterMimeType.php(41): OCA\Keeweb\Migration\RegisterMimeType->registerForNewFiles()
                 #1 /var/www/nextcloud/lib/private/Repair.php(127): OCA\Keeweb\Migration\RegisterMimeType->run()
                 #2 /var/www/nextcloud/lib/private/legacy/OC_App.php(836): OC\Repair->run()
                 #3 /var/www/nextcloud/lib/private/Installer.php(166): OC_App::executeRepairSteps()
                 #4 /var/www/nextcloud/lib/private/legacy/OC_App.php(264): OC\Installer->installApp()
                 #5 /var/www/nextcloud/lib/private/Updater.php(431): OC_App->enable()
                 #6 /var/www/nextcloud/lib/private/Updater.php(284): OC\Updater->upgradeAppStoreApps()
                 #7 /var/www/nextcloud/lib/private/Updater.php(140): OC\Updater->doUpgrade()
                 #8 /var/www/nextcloud/core/Command/Upgrade.php(222): OC\Updater->upgrade()
                 #9 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\Upgrade->execute()
                 #10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
                 #11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
                 #12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
                 #13 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
                 #14 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
                 #15 /var/www/nextcloud/occ(11): require_once('...')
                 #16 {main}
```

I wonder why that happens as the app was/is listed as compatible with NC v28.

**Comment by arnowelzel** [comment]
The problem is, that the **old version** is not compatible to NC 28. However when upgrading to NC 28, the old app version is still in place. I don't really how to fix this, since the **old version** installed on your system would need to be modified to be able to be upgraded in NC 28. The only workaround is to deactivate and remove the app, the upgrade to NC 28 and then install it again.

Unfortunately I also conside this app as "dead", since the upstream is also not maintained any longer. Also see https://github.com/keeweb/keeweb/issues/2022 - as far I know, no one replied to this request so far and I have neither the time nor the knowledge required to maintain KeeWeb itself.

**Comment by bcutter** [comment]
After the NC v28 update keeweb was listed as:

`keeweb: 0.6.17 (installed 0.6.17)`

Enabling the app seems to make it work again (not fully tested yet). There should have been an update for versions < NC 28 to prepare the app and avoid such update issue as you mentioned @arnowelze .

**Comment by arnowelzel** [comment]
Maybe I did not state this clear enough: but KeeWeb for Nextcloud is "dead". There won't be any updates at all as long as the KeeWeb upstream is not maintained any longer, sorry. I will add a more visible note about this in the README.

**Comment by BastianBalthasarBux** [comment]
Sorry Arno, but while antelle searches for a new maintainer for a while now, the project is not left "unmaintained". Just look at the upstream repo, which is still actively maintained, gets commits, merges etc., although the speed of development lowered.

**Comment by arnowelzel** [comment]
The status was not like this on April 3, 2024.

If there is an official maintainer and a new release for Keeweb itself, I will use the new version and revert the warning notice for Nextcloud. But for now the latest release is still from 2021 and the issue https://github.com/keeweb/keeweb/issues/2022 is still not marked as "solved", sorry!

Also see: https://github.com/keeweb/keeweb/releases

**Comment by Githopp192** [comment]
same: 

The question could be - why nc tries to update apps, which are not yet supported anymore the updated nc release ? 
(normally i thinks such apps should be disabled during nc upgrade process ?!)

Error: Undefined constant OCA\Keeweb\Migration\RegisterMimeType::CUSTOM_MIMETYPEALIASES in /var/www/html/nextcloud/apps/keeweb/lib/Migration/RegisterMimeType.php:25									
Stack trace:									
#0 /var/www/html/nextcloud/apps/keeweb/lib/Migration/RegisterMimeType.php(41): OCA\Keeweb\Migration\RegisterMimeType->registerForNewFiles()									
#1 /var/www/html/nextcloud/lib/private/Repair.php(128): OCA\Keeweb\Migration\RegisterMimeType->run()									
#2 /var/www/html/nextcloud/lib/private/legacy/OC_App.php(836): OC\Repair->run()									
#3 /var/www/html/nextcloud/lib/private/Installer.php(166): OC_App::executeRepairSteps()									
#4 /var/www/html/nextcloud/lib/private/legacy/OC_App.php(264): OC\Installer->installApp()									
#5 /var/www/html/nextcloud/lib/private/Updater.php(435): OC_App->enable()									
#6 /var/www/html/nextcloud/lib/private/Updater.php(288): OC\Updater->upgradeAppStoreApps()									
#7 /var/www/html/nextcloud/lib/private/Updater.php(144): OC\Updater->doUpgrade()									
#8 /var/www/html/nextcloud/core/Command/Upgrade.php(222): OC\Updater->upgrade()									
#9 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\Upgrade->execute()									
#10 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()									
#11 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()									
#12 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()									
#13 /var/www/html/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()									
#14 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()									
#15 /var/www/html/nextcloud/occ(11): require_once('...')									
#16 {main}
