### ISSUE TITLE
Build fails on 16.04

### ISSUE THREAD

**Issue by fthiery** [jhass/nextcloud-keeweb#51]
Hi there; first of all i'm sorry i might be missing an obvious point, but i tried to follow the dev env instructions and am stuck; this is on a fresh ubuntu 16.04.

I am trying to help fix https://github.com/keeweb/keeweb/issues/656 ("Browser autofills master password and search box") by building a fresh version of nextcloud-keeweb that would use the latest keeweb version.

```
# git clone https://github.com/jhass/nextcloud-keeweb.git
# cd nextcloud-keeweb
# git clone -b stable12 https://github.com/nextcloud/server.git nextcloud
# ln -sf "$(pwd)/keeweb" nextcloud/apps
# git clone https://github.com/keeweb/keeweb.git keeweb-source
# apt-get install npm
# grunt install grunt bower
# LANG=C ./bin/build  master
Removing npm-debug.log
Already on 'master'
Your branch is up-to-date with 'origin/master'.
refs/heads/master
Already up-to-date.
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "uninstall" "--save-dev" "electron-prebuilt"
npm ERR! node v4.2.6
[npm-debug.log.txt](https://github.com/jhass/nextcloud-keeweb/files/1061741/npm-debug.log.txt)


npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/usr/share/npm/lib/install/deps.js:438:3)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:234:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/usr/share/npm/lib/install/deps.js:230:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/usr/share/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fthiery/nextcloud-keeweb/keeweb-source/npm-debug.log
```

**Comment by jhass** [comment]
Maybe your `npm` is too old, I have `4.61` locally.

**Comment by fthiery** [comment]
It worked with:

```
git clone https://github.com/jhass/nextcloud-keeweb.git
cd nextcloud-keeweb
git clone -b stable12 https://github.com/nextcloud/server.git nextcloud
ln -sf "$(pwd)/keeweb" nextcloud/apps
git clone https://github.com/keeweb/keeweb.git keeweb-source
curl -sL https://deb.nodesource.com/setup_7.x | sudo bash -
sudo apt-get install nodejs
sudo npm -g install grunt bower
LANG=C ./bin/build  master
...
> keytar@3.0.2 install /home/fthiery/nextcloud-keeweb/keeweb-source/node_modules/keytar
> node-gyp rebuild

/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-79-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fthiery/nextcloud-keeweb/keeweb-source/node_modules/keytar
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
...
make: Entering directory '/home/fthiery/nextcloud-keeweb/keeweb-source/node_modules/macos-alias/build'
  CXX(target) Release/obj.target/volume/src/volume.o
../src/volume.cc:9:2: error: #error This platform is not implemented yet
 #error This platform is not implemented yet
  ^
../src/volume.cc: In function 'void Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)':
../src/volume.cc:16:49: error: 'MethodGetVolumeName' was not declared in this scope
     Nan::GetFunction(Nan::New<FunctionTemplate>(MethodGetVolumeName)).ToLocalChecked());
                                                 ^
volume.target.mk:94: recipe for target 'Release/obj.target/volume/src/volume.o' failed
make: *** [Release/obj.target/volume/src/volume.o] Error 1
make: Leaving directory '/home/fthiery/nextcloud-keeweb/keeweb-source/node_modules/macos-alias/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-79-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fthiery/nextcloud-keeweb/keeweb-source/node_modules/macos-alias
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
...
Running "sign-html:app" (sign-html) task
>> Private key is missing, app html will not be signed.

Done.


Execution Time (2017-06-09 10:39:10 UTC+2)
loading tasks                 9.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 31%
bower-install-simple:install    2s  ▇▇▇▇ 7%
eslint:app                    3.9s  ▇▇▇▇▇▇▇ 13%
webpack:js                    6.1s  ▇▇▇▇▇▇▇▇▇▇ 21%
uglify:app                    4.3s  ▇▇▇▇▇▇▇ 15%
uglify:vendor                 1.2s  ▇▇ 4%
postcss:dist                  2.1s  ▇▇▇▇ 7%
Total 29.1s
```

It looks like it succeeded anyway. How do i build a new app package for nexctcloud for testing purposes ?

**Comment by fthiery** [comment]
Found it, i did: 

```
# cd keeweb
# make dist
```
The tar is in build/artifacts/appstore/keeweb.tar.gz and can be installed in the nextcloud app folder

**Comment by fthiery** [comment]
Btw to build the development version of keeweb, the appropriate command is
`./bin/build develop`

**Comment by fthiery** [comment]
And i have good news, the fix that the keeweb author did fixes the fact that the master password and search box get autofilled by the browser with the nextcloud's login and password.

**Comment by fthiery** [comment]
I created a pull request to improve the doc
https://github.com/jhass/nextcloud-keeweb/pull/52
